# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Autocorrect swfit code style with swiftlint"
  lane :lint do
    swiftlint(mode: :autocorrect, config_file: '.swiftlint.yml')
  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: 'FiveSenses')
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    swiftlint(mode: :lint, ignore_exit_status: true)
    ensure_git_status_clean
    increment_build_number
    commit_version_bump
    snapshot
    # match(type: "appstore") # more information: https://codesigning.guide
    cert(output_path: "provisioning")
    sigh(output_path: "provisioning")
    gym(scheme: 'FiveSenses')
    pilot
    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Push a new release build to the App Store"
  lane :release do
    build_app(scheme: 'FiveSenses')
    upload_to_app_store
  end
end
